zustand, filter admin panel, active toggle
Sm1l/webrocket pull request #4
Opened 2024-06-16 18:17 UTC by Sm1l

1. Прикрутил зустанд
2. Сделал фильтр по дате и активости. Красная рамка, если нет ответа более 2 дней.
3. Активность/неактивность карточки обновляется в файрбэйс, потом уже обновляется зустанд

2024-06-17 06:12 UTC, Lioger requested changes

2024-06-17 06:12 UTC, Lioger commented on src/assets/variables.scss
> +  --color-red: #f03a22;
Раз уж используешь SCSS, то тогда лучше переменные SCSS использовать:
$color-red: #f03a22;
И по коду не нужно выражение var(...)

2024-06-17 06:12 UTC, Lioger commented on src/components/AdminFeedback/AdminFeedback.module.scss
> +  flex-direction: row;
Значение по умолчанию, прописывать явно не обязательно

2024-06-17 06:12 UTC, Lioger commented on src/components/AdminFeedback/AdminFeedback.tsx
> +  const urgentFeedbacks = (date: number) => {
isUrgentDate. По факту ты не передаешь сюда фидбек. И число 172800000 лучше вынести в переменную константу типо TIME_TO_URGENT

2024-06-17 06:12 UTC, Lioger commented on src/components/AdminFeedback/AdminFeedback.tsx
> +    if (urgentDate < dateNow) {
return urgentDate < dateNow

2024-06-17 06:12 UTC, Lioger commented on src/components/AdminFeedback/AdminFeedback.tsx
> +  const feedbackClass = (date: number, active: boolean) => {
getFeedbackClass

2024-06-17 06:12 UTC, Lioger commented on src/components/AdminFilter/AdminFilter.tsx
> +      sortFeedbacks(sortByDate, sortByActive);
Этот вызов функции нужен? В эффекте выше она вызывается

2024-06-17 06:12 UTC, Lioger commented on src/components/AdminPanel/AdminPanel.tsx
>        {loading ? (
Присмотрись к новому механизму React.Suspense

2024-06-17 06:12 UTC, Lioger commented on src/components/Button/Button.tsx
> +      className={active === true ? `${styles.button} ${styles.buttonActive}` : styles.button}
className={`${styles.button} ${active ? styles.buttonActive : null}`}

2024-06-17 06:12 UTC, Lioger commented on src/store/feedbackStore.ts
> +export const sortFeedbacks = (dateOrder: "newest" | "oldest", activeOrder: "activeFirst" | "inactiveFirst") => {
Так получается, что ты не фильтр реализовал, а сортировку?

2024-06-17 06:12 UTC, Lioger commented on src/components/AdminPanel/AdminPanel.tsx
> +  }, [dataIsChangedInFirebase]);
Тебе нет смысла дергать список элементов, если изменение стриггерил ты сам на фронте и никто другой больше не мог это сделать. Тебе достаточно в зустанд сторе поменять поле active у одного item

2024-06-17 06:12 UTC, Lioger commented on src/components/AdminPanel/AdminPanel.tsx
> +  }, [dataIsChangedInFirebase]);
Поэтому вообще не вижу смысла в стейте dataIsChangedInFirebase

2024-06-17 18:21 UTC, Sm1l commented on src/assets/variables.scss
> +  --color-red: #f03a22;
Этот вопрос решили)

2024-06-17 18:21 UTC, Sm1l commented on src/components/AdminFeedback/AdminFeedback.module.scss
> +  flex-direction: row;
+

2024-06-17 19:00 UTC, Sm1l commented on src/components/AdminFeedback/AdminFeedback.tsx
> +  const urgentFeedbacks = (date: number) => {
Согласен, сделал. Только не понял фразу№: "По факту ты не передаешь сюда фидбек."

2024-06-17 19:01 UTC, Sm1l commented on src/components/AdminFeedback/AdminFeedback.tsx
> +    if (urgentDate < dateNow) {
гораздо проще, согласен, надо привынуть к такому)

2024-06-17 19:02 UTC, Sm1l commented on src/components/AdminFeedback/AdminFeedback.tsx
> +  const feedbackClass = (date: number, active: boolean) => {
нейминг, согласен

2024-06-17 19:03 UTC, Sm1l commented on src/components/AdminFilter/AdminFilter.tsx
> +      sortFeedbacks(sortByDate, sortByActive);
согласен, не нужен, в 3 местах убрал, в одном забыл) Как ты все видишь))

2024-06-17 20:01 UTC, Sm1l commented on src/components/AdminPanel/AdminPanel.tsx
> +  }, [dataIsChangedInFirebase]);
Идею понял. 
Сделал через .then что после того, как я обновил поле active в firebase,  я обновляю его в state.
Но мне все-равно пришлось оставить триггер storeIsChanged, за который дергать, чтобы после изменения состояния active сразу делать сортировку(да, я сделал сортировку, вместо фильтрации))))). Функцию сортировки я не хочу выносить из компонента, поэтому дергаю за нее внутри соответствующего компонента. Пока storeIsChanged я сделал просто state, но, возможно стоит его вынести в store?

2024-06-17 20:02 UTC, Sm1l commented on src/components/AdminPanel/AdminPanel.tsx
>        {loading ? (
Принял. Это я почитаю завтра, пока не менял)

2024-06-17 20:09 UTC, Sm1l commented on src/components/Button/Button.tsx
> +      className={active === true ? `${styles.button} ${styles.buttonActive}` : styles.button}
согласен, так читабельнее)

2024-06-17 20:10 UTC, Sm1l commented on src/store/feedbackStore.ts
> +export const sortFeedbacks = (dateOrder: "newest" | "oldest", activeOrder: "activeFirst" | "inactiveFirst") => {
Да, что-то я перепутал))) Могу прикрутить и фильтр)

2024-06-18 06:02 UTC, Lioger commented on src/components/AdminFeedback/AdminFeedback.tsx
> +  const urgentFeedbacks = (date: number) => {
@Sm1l речь о том, что ты сюда передаешь просто дату - timastamp, а не весь объект feedback. Функцию в дальнейшем (условно) можно будет еще для чего-то использовать

2024-06-18 06:06 UTC, Lioger commented on src/store/feedbackStore.ts
> +export const sortFeedbacks = (dateOrder: "newest" | "oldest", activeOrder: "activeFirst" | "inactiveFirst") => {
@Sm1l жалко конечно уже реализованный механизм выпиливать, но по факту он нам не нужен. Давай из firebase будем тянуть записи отсортированными по дате, т.е. чтобы в списке они были в хронологическом порядке. Помимо этого сверху будет фильтр из трех кнопок: Все (по умолчанию активная), Активные, Отвеченные. Переключение по ним на стороне UI просто фильтрует отображаемый снизу список

2024-06-18 06:56 UTC, merged