reworking the data type in firebase, delete function
Sm1l/webrocket pull request #5
Opened 2024-06-18 21:20 UTC by Sm1l

Начал делать функцию удаления карточки отзыва...оказалось, что в корне не правильно использовал firebase: там существуют коллекции и документы, и одно в другом находится не может. 
https://firebase.google.com/docs/firestore/query-data/get-data?_gl=1*109ki9t*_up*MQ..*_ga*MTUwNDk2MDQwMS4xNzE4NzMzOTI0*_ga_CW55HF8NVT*MTcxODczMzkyMy4xLjAuMTcxODczMzkyMy4wLjAuMA..#web_2
(просто если будет интересно, хотя ты, наверное, уже с этим сталкивался)
Поэтому пришлось все переделать, что касалось firebase...
Сделал функцию удаления карточки отзыва.

А еще не правильно реализовал механизм тоггла, а именно:
функция тоггла поля active в firebase могла зарезолвиться даже если, например, передавать в нее неправильный id и из-за этого, функция функция тоггла поля active в Store могла сработать....короче, как понял, нужно было явно выкидывать ошибки, а не делать else-if с console.log...

2024-06-20 11:08 UTC, Lioger approved these changes

2024-06-20 11:08 UTC, Lioger commented on src/firebase/deleteFeedbackFromFirebase.ts
> +    await deleteDoc(docRef);
То есть вот эта функция могла отработать, если передать id, который не существует на самом деле?

2024-06-20 13:16 UTC, Sm1l commented
Я добавил фильтр. И все-таки оставил пока сортировку по дате, вроде подружил их)
После аппрува этого пулреквеста (обновлю локальный master) и тогда я создам здесь ветку  dev, из которой уже буду создавать ветки для тасков.

2024-06-21 06:09 UTC, Lioger requested changes

2024-06-21 06:09 UTC, Lioger commented on src/components/AdminFilter/AdminFilter.tsx
> +      <Button text="inactive" type="button" active={filterBy === "inactive"} onClick={filterByInactiveHandleClick} />
Так-с давай мы кнопкам добавим data-value={props.text}, а в функции обработчике клика будем извлекать e.target.dataset.value. Таким образом у нас будет 1 функция обработчик вместо трех

2024-06-21 06:09 UTC, Lioger commented on src/components/AdminPanel/AdminPanel.tsx
> +  const KOSTYA_ID = "Yeu5qZnTbIWyRuzZigK8BmgVDSt2";
Давай сделаем объект наших админов и вынесем его вне компонента:
const ADMINS = { Yeu5qZnTbIWyRuzZigK8BmgVDSt2: "Костя", ObpSKBjHoAUG1K0MFNr3rlF50Ln1: "Никита" }

2024-06-21 06:09 UTC, Lioger commented on src/components/AdminPanel/AdminPanel.tsx
>    const returnName = (adminId: string) => {
А вот тут переделаем так:
const returnName = (adminId: string) => ADMINS[adminId] ?? "Админ";

2024-06-21 06:09 UTC, Lioger commented on src/components/AdminPanel/AdminPanel.tsx
> +    fetchData();
Как будто это ненужная операция. Почему бы не поставить storeIsChanged по умолчанию false, а тут просто вызывать функцию fetchFeedbacks?

2024-06-21 06:09 UTC, Lioger commented on src/components/AdminFilter/AdminFilter.tsx
> +      <Button text="inactive" type="button" active={filterBy === "inactive"} onClick={filterByInactiveHandleClick} />
или будем передавать специальный prop value

2024-06-21 06:09 UTC, Lioger commented on src/components/AdminSort/AdminSort.tsx
> +        active={sortByDate === "oldest"}
Здесь тоже можно объединить

2024-06-22 10:45 UTC, merged

2024-06-27 06:04 UTC, Lioger commented on src/components/AdminFeedbackList/AdminFeedbackList.tsx
> +      {filteredFeedbacks?.length === 0 ? (
Тут лучше переверни условие. Начни с того, когда {filteredFeedbacks?.length ? ... : ...}. Сейчас получается, что, если filteredFeedbacks === undefined, то мы будем пытаться список отрендерить. А нам лучше если !!filteredFeedbacks === false или !!filteredFeedbacks.length === false