modal delete
Sm1l/webrocket pull request #8
Opened 2024-06-22 13:46 UTC by Sm1l

Добавил модалку для удаления карточки братной связи.
Сделал кнопку удаления видимой только тогда, когда карточка отмечена как "прочитанная".

2024-06-27 06:18 UTC, Lioger requested changes

2024-06-27 06:18 UTC, Lioger commented on src/components/AdminContent/AdminContent.tsx
>        {isAdmin === true && <AdminPanel adminId={adminId} />}
закомменченное надо?

2024-06-27 06:18 UTC, Lioger commented on src/components/DeleteModal/DeleteModal.module.scss
> +  flex-direction: row;
не обязательно явно прописывать

2024-06-27 06:18 UTC, Lioger commented on src/components/DeleteModal/DeleteModal.tsx
> +    };
До конца не понимаю, зачем здесь делать именно через return колбека

document.body.style.overflow = modalIsVisible ? "hidden" : "unset"; - так не сработает или лишние итерации будут?

2024-06-28 17:44 UTC, Sm1l commented on src/components/AdminContent/AdminContent.tsx
>        {isAdmin === true && <AdminPanel adminId={adminId} />}
Прошу прощения, делал для себя, чтобы не надо было пароль вводить и сразу показывало нужную секцию)
Все поправил!

2024-06-28 17:45 UTC, Sm1l commented on src/components/DeleteModal/DeleteModal.module.scss
> +  flex-direction: row;
+++

2024-06-28 18:23 UTC, Sm1l commented on src/components/DeleteModal/DeleteModal.tsx
> +    };
Очень хороший вопрос!
В теории ты прав и  вот так
useEffect(() => {
    document.body.style.overflow = modalIsVisible ? "hidden" : "unset";
  }, [modalIsVisible]);
все должно работать корректно, но, блин, не работает))) не восстанавливается scroll.
Помучал пару ИИ, но толком ответ не нашел пока...

Gpt написал, что 
Удаление свойства overflow должно происходить всегда: Убедитесь, что document.body.style.overflow всегда сбрасывается, независимо от состояния modalIsVisible.

Phind написал:
1. Скорость закрытия модального окна: Если модальное окно закрывается очень быстро, возможно, браузеру не дает достаточно времени для перерисовки и применения нового значения overflow. Это может привести к тому, что скролл не будет восстановлен сразу.
2. Анимации или другие изменения DOM: Если в вашем приложении используются анимации или другие изменения DOM, которые происходят одновременно с открытием или закрытием модального окна, они могут влиять на процесс восстановления скролла.
3. Браузерные особенности: Разные браузеры могут по-разному обрабатывать изменения стилей и анимации. Возможно, в вашем случае браузер не успевает корректно обработать изменение overflow.

НО я пока до сути не докопался....

2024-06-30 22:01 UTC, merged