review section
Sm1l/webrocket pull request #9
Opened 2024-06-23 07:44 UTC by Sm1l

Секция с отзывами

2024-06-27 06:12 UTC, Lioger requested changes

2024-06-27 06:12 UTC, Lioger commented on src/components/Bubble/Bubble.module.scss
> +  // animation: flyOrbital 6000ms linear;
комменты

2024-06-27 06:12 UTC, Lioger commented on src/components/Review/Review.module.scss
> +@media (width >= 1024px) {
для своего удобства заведи себе переменные с брейкпоинтами ($sm = 425; $md = 768px; $lg = 1024px, $xl = 1300px, $xxl = 1600px)

2024-06-27 06:12 UTC, Lioger commented on src/components/ReviewCard/ReviewCard.module.scss
> +  vertical-align: middle;
тут точно нужны vertical-align и float? Эти свойства сейчас стараются избегать

2024-06-28 17:29 UTC, Sm1l commented on src/components/Review/Review.module.scss
> +@media (width >= 1024px) {
Согласен!
Это я записал, еще разберусь с этим.
Не хочет работать в таком виде:
@media (width >= var(--md)) {}
Что странно, ведь в таком виде:
 @media (min-width: var(--md)) {}
прекрасно работает
Не хотелось бы переделывать все, т.к. , как я понял, (width >=) более современный и понятный синтаксис.
Я еще посмотрю это!

2024-06-28 17:30 UTC, Sm1l commented on src/components/Bubble/Bubble.module.scss
> +  // animation: flyOrbital 6000ms linear;
+

2024-06-28 17:35 UTC, Sm1l commented on src/components/ReviewCard/ReviewCard.module.scss
> +  vertical-align: middle;
vertical-align вроде норм получилось убрать, а float в данном случае ломает все( 
Тут я подсмотрел, прикольное обтекание полукругом получается, посмотришь! 
Но, если что, вид карточки можно и поменять, это я экспериментирую)

2024-06-28 17:41 UTC, Lioger commented on src/components/Review/Review.module.scss
> +@media (width >= 1024px) {
Я везде по старинке делаю)))

2024-06-28 17:42 UTC, Lioger approved these changes

2024-06-28 18:33 UTC, merged